version: 2.1
jobs: 
  build: 
    working_directory: ~/circleci-codeclimate
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:    
          name: Run tests
          command: npm test
      - run:
          name: Generate coverage report
          command: npm run cover

      - store_artifacts: # Save tests results as artifacts
          path: test-results.xml
          prefix: tests

      - store_artifacts: # Save coverage reports as artifacts
          path: coverage
          prefix: coverage
        